src/Entity/Property.php
<?php

namespace App\Entity;


class Property
{
    private $_id;
    private $_url;
    private $_title;
    private $_city;
    private $_picture;


    public function __construct(
        int $_id,
        string $_url,
        string $_title,
        string $_city,
        string $_picture
    ){
        $this->_id = $_id;
        $this->_url = $_url;
        $this->_title = $_title;
        $this->_city = $_city;
        $this->_picture = $_picture;
    }

    public function getId():int
    {
        return $this->_id;
    }


    public function getUrl():string
    {
        return $this->_url;
    }


    public function getTitle():string
    {
        return $this->_title;
    }

    public function getCity():string
    {
        return $this->_city;
    }

    public function getPicture():string
    {
        return $this->_picture;
    }




}

src/Controller/PropertiesController.php
<?php

namespace App\Controller;

use App\UseCases\Source\Get\{UseCase as UseCaseGet, Request as RequestGet};
use App\UseCases\Source\Order\{UseCase as UseCaseOrder, Request as RequestOrder};
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;

class PropertiesController extends Controller
{

    private $_useCaseGet;
    private $_useCaseOrder;


    public function __construct(
        UseCaseGet $_useCaseGet,
        UseCaseOrder $_useCaseOrder
    ){
        $this->_useCaseGet = $_useCaseGet;
        $this->_useCaseOrder = $_useCaseOrder;
    }


    /**
     * @Route("/properties/{field}/{order}", name="properties", )
     */
    public function index(string $field = "ID", string $order = "ASC")
    {
        $orderedProperties = $this->getOrderedProperties($field, $order);

        return $this->render('default/properties.html.twig', [
            'properties' => $orderedProperties,
            'field' => $field,
            'order' => $order,
        ]);
    }

    /**
     * @Route("/download/{field}/{order}", name="download", )
     */
    public function download(string $field = "ID", string $order = "ASC")
    {
        $orderedProperties = $this->getOrderedProperties($field, $order);
        return $this->json(
            $orderedProperties,
            200,
            [
                'Content-Disposition' =>  'attachment',
            ]
        );
    }

    private function getOrderedProperties(
        string $field = "ID",
        string $order = "ASC"
    ): array
    {
        $request = new RequestGet(getenv("PATH_XML"));
        $response = $this->_useCaseGet->execute($request);
        $properties = $response->getData();

        $requestOrder = new RequestOrder($field, $order, $properties);
        $responseOrder = $this->_useCaseOrder->execute($requestOrder);
        return $responseOrder->getData();
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        {% block stylesheets %}{% endblock %}
    </head>
    <body>
        {% block body %}{% endblock %}
        {% block javascripts %}{% endblock %}
    </body>
</html>

templates/default/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello {{ controller_name }}!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Helloooo {{ controller_name }}! ✅</h1>
    <a href="{{ path('user', {'name': 'pepito'}) }}">
        pepito
    </a>
</div>
{% endblock %}

templates/default/properties.html.twig
{% extends 'base.html.twig' %}

{% block title %}Properties{% endblock %}

{% block body %}
    <style>
        .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
        .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
    </style>

    <div>
        <a target="_blank" href="{{ path('download', {'field': field, 'order': order}) }}">
            Download
        </a>
    </div>
    <div class="example-wrapper">
        <table>
            <tr>
                <td>ID
                    <a href="{{ path('properties', {'field': 'ID', 'order': 'ASC'}) }}">
                        &uarr;
                    </a>
                    <a href="{{ path('properties', {'field': 'ID', 'order': 'DESC'}) }}">
                        &darr;
                    </a>
                </td>
                <td>
                    Title
                    <a href="{{ path('properties', {'field': 'TITLE', 'order': 'ASC'}) }}">
                        &uarr;
                    </a>
                    <a href="{{ path('properties', {'field': 'TITLE', 'order': 'DESC'}) }}">
                        &darr;
                    </a>
                </td>
                <td>
                    Link
                    <a href="{{ path('properties', {'field': 'LINK', 'order': 'ASC'}) }}">
                        &uarr;
                    </a>
                    <a href="{{ path('properties', {'field': 'LINK', 'order': 'DESC'}) }}">
                        &darr;
                    </a>
                </td>
                <td>
                    City
                    <a href="{{ path('properties', {'field': 'CITY', 'order': 'ASC'}) }}">
                        &uarr;
                    </a>
                    <a href="{{ path('properties', {'field': 'CITY', 'order': 'DESC'}) }}">
                        &darr;
                    </a>
                </td>
                <td>
                    Picture
                    <a href="{{ path('properties', {'field': 'PICTURE', 'order': 'ASC'}) }}">
                        &uarr;
                    </a>
                    <a href="{{ path('properties', {'field': 'PICTURE', 'order': 'DESC'}) }}">
                        &darr;
                    </a>
                </td>
            </tr>
            {% for property in properties %}
                <tr>
                    <td>{{ property.id }}</td>
                    <td>{{ property.title }}</td>
                    <td>{{ property.url }}</td>
                    <td>{{ property.city }}</td>
                    <td><img src="{{ property.picture }}"/></td>
                </tr>
            {% endfor %}
        </table>

    </div>
{% endblock %}